# =================================================================
# Base Configuration
# -----------------------------------------------------------------
# 这个文件定义了所有实验共享的默认参数。
# 具体的实验配置文件可以覆盖这些值。
# =================================================================

# --- 随机种子 ---
# 用于保证实验的可复现性
seed: 42

# --- 数据集配置 ---
dataset:
  # 数据集名称，会被用作 data/processed/ 目录下的子文件夹名
  name: "wesad_early_fusion"
  # WESAD 数据集的所有可用受试者
  all_subjects: ['S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'S9', 'S10', 'S11', 'S13', 'S14', 'S15', 'S16', 'S17']
  # 从训练集中划分出作为验证集的比例
  val_split_ratio: 0.2
  # 预处理时定义的所有通道名列表
  all_channel_names: ['chest_ACC_x', 'chest_ACC_y', 'chest_ACC_z', 'chest_ECG', 'chest_EDA', 'chest_EMG', 'chest_Resp',
                      'wrist_ACC_x', 'wrist_ACC_y', 'wrist_ACC_z', 'wrist_BVP', 'wrist_EDA']
  # --- 新增: 为 feature_sequence 定义核心维度 ---
  sequence_params:
    sequence_length: 10
    step: 1

# --- 模型配置 ---
model:
  # 压力、娱乐、中性
  num_classes: 3

  params: {}

# --- 训练器配置 ---
trainer:
  # 训练的总轮数 (Epochs)
  epochs: 50
  # 学习率
  learning_rate: 0.001
  # 批大小
  batch_size: 64
  # 数据加载器的工作线程数
  num_workers: 0  # 增加了线程会导致tqdm进度条显示异常,而且线程数越多，速度反而越慢
  # --- 类别加权开关 ---
  use_class_weights: false
  # --- 早停 (Early Stopping) 配置 ---
  early_stopping:
    # 是否启用早停
    enabled: true
    # 'patience' 指的是验证集性能在多少个epoch内没有提升就停止训练
    # 如果验证损失连续 5 个 epoch 都没有变得更低，训练就会终止
    patience: 5
    # 'delta' 指的是性能提升的最小阈值，低于此阈值不算提升
    delta: 0.0001
    # 监控的指标，可以是 'val_loss' (越小越好) 或 'val_accuracy' (越大越好)
    monitor: 'val_loss'
    # 模式，'min' 表示监控的指标越小越好，'max' 则反之
    mode: 'min'

