# src/configs/ecg_cnn.yaml

# 继承基础配置
defaults:
  - base_config

# --- 数据集配置 (覆盖/指定本次实验的特定设置) ---
dataset:
  # 定义本次实验使用的受试者
  all_subjects: ['S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'S9']
  # 定义本次实验使用的通道
  channels_to_use: ['chest_ECG']

# --- 模型配置 ---
model:
  name: "cnn_1d"
  params:
    in_channels: 3 # 输入通道数，根据 channels_to_use 的长度决定

# --- 训练器配置 ---
#trainer:
#  num_workers: 0

# --- 融合方式 ---
fusion:
  type: "early" # 虽然是单通道，但数据格式遵循早期融合