# configs/feature_mlp.yaml

defaults:
  - base_config

# --- 数据集配置 ---
# *** 使用 feature_fusion 数据 ***
dataset:
  name: "wesad_feature_fusion"
  channels_to_use: null # 对于特征融合，我们使用所有预提取的特征，不再选择通道

# --- 模型配置 ---
# *** 使用最简单的 MLP 模型 ***
model:
  name: "mlp"
  params:
    in_features: 24 # 这是我们预处理时生成的特征数量
    hidden_layers: [256, 128, 64] # 可以调整网络结构
    dropout: 0.5

# --- 训练器配置 ---
trainer:
  epochs: 100
  learning_rate: 0.001
  early_stopping:
    patience: 15

# --- 融合方式配置 ---
# *** 中期/晚期特征融合 ***
fusion:
  type: "feature"