# configs/hrv_ctg.yaml

defaults:
  - base_config

dataset:
  name: "wesad_hrv_sequence"

model:
  name: "cnn_transformer_gru" # <--- 使用新模型
  in_channels: 1 # HRV 序列是单通道
  num_classes: 3
  params:
    # --- 模型超参数 ---
    cnn_out_channels: 64
    d_model: 64  # Transformer的维度，需要与cnn_out_channels匹配
    nhead: 4     # 注意力头数
    num_transformer_layers: 2
    gru_hidden_size: 128
    gru_num_layers: 2
    dropout: 0.4

trainer:
  epochs: 150 # 复杂模型可能需要更多轮次
  learning_rate: 0.0001
  batch_size: 64
  early_stopping:
    patience: 20 # 给复杂模型更多耐心

fusion:
  type: "hrv_sequence"