# src/configs/hrv_cnngru.yaml
defaults:
  - base_config

dataset:
  name: "wesad_hrv_sequence" # <--- 使用新数据

model:
  name: "cnn_gru" # <--- 用 CNN-GRU 验证
  params:
    cnn_out_channels: 32
    gru_hidden_size: 64

trainer:
  epochs: 100
  learning_rate: 0.001
  batch_size: 64
  early_stopping:
    patience: 15

fusion:
  type: "hrv_sequence" # <--- 新的类型