# src/configs/hrv_transformer.yaml
defaults:
  - base_config

dataset:
  name: "wesad_hrv_sequence"

model:
  name: "transformer" # <--- 再用 Transformer 验证
  params:
    d_model: 64 # HRV 序列长度较短(240)，可以适当减小模型维度
    nhead: 8
    num_layers: 3
    dropout: 0.3

trainer:
  epochs: 100
  learning_rate: 0.0001
  batch_size: 64

fusion:
  type: "hrv_sequence"